"""Test-script generation — three tiers.

- **status**  — deterministic: asserts the success status code.
- **schema**  — deterministic: asserts the response body has the declared fields.
- **business**— inferred, the one non-deterministic part; gated behind a flag and
  shipped OFF by default. status + schema are the trusted tiers.

Output is a Postman ``event`` (a ``test`` script) targeting the request item.
"""

from __future__ import annotations

from typing import Optional

from postman_mcp.models import BodyModel, ResponseModel, RouteModel


def _success_status(route: RouteModel) -> int:
    for resp in route.responses:
        if 200 <= resp.status < 300:
            return resp.status
    # Sensible default per method when the spec declares no 2xx.
    return 201 if route.method.upper() == "POST" else 200


def _success_body(route: RouteModel) -> Optional[BodyModel]:
    for resp in route.responses:
        if 200 <= resp.status < 300 and resp.body is not None:
            return resp.body
    return None


def build_test_script(route: RouteModel, *, business: bool = False) -> str:
    """Build the test-script source for a route."""
    status = _success_status(route)
    lines: list[str] = [
        "// Generated by postman-mcp — status + schema tiers",
        f'pm.test("status is {status}", function () {{',
        f"    pm.response.to.have.status({status});",
        "});",
    ]

    body = _success_body(route)
    if body and body.fields:
        field_names = [f.name for f in body.fields if f.required] or [
            f.name for f in body.fields
        ]
        lines.append("")
        lines.append('pm.test("response matches schema", function () {')
        lines.append("    var data = pm.response.json();")
        for name in field_names:
            lines.append(f'    pm.expect(data).to.have.property("{name}");')
        lines.append("});")

    if business:
        # The one non-deterministic tier — emitted only when explicitly enabled.
        hint = _business_hint(route)
        if hint:
            lines.append("")
            lines.append("// business-logic assertion (inferred — verify before trust)")
            lines.append(hint)

    return "\n".join(lines)


def _business_hint(route: RouteModel) -> Optional[str]:
    """A best-effort business assertion from field names. Inferred only."""
    if route.body:
        for field in route.body.fields:
            if "amount" in field.name.lower() or "price" in field.name.lower():
                return (
                    'pm.test("business(amount > 0)", function () {\n'
                    "    var data = pm.response.json();\n"
                    f'    if (data.{field.name} !== undefined) pm.expect(data.{field.name}).to.be.above(0);\n'
                    "});"
                )
    return None
